/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lopez.julz;

import db.CollectiblesDao;
import db.DCRSummaryTransactionsDao;
import db.DatabaseConnection;
import db.OCLMonthlyDao;
import db.ORAssigningDao;
import db.ServiceAccountsDao;
import db.TransactionDetailsDao;
import db.TransactionIndexDao;
import db.TransactionPaymentDetailsDao;
import helpers.ConfigFileHelpers;
import helpers.Notifiers;
import helpers.ObjectHelpers;
import helpers.TransactionsPrint;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.Book;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.RoundingMode;
import java.sql.Connection;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;
import pojos.Collectibles;
import pojos.DCRSummaryTransactions;
import pojos.OCLMonthly;
import pojos.ORAssigning;
import pojos.Server;
import pojos.ServiceAccounts;
import pojos.TransactionDetails;
import pojos.TransactionIndex;
import pojos.TransactionPaymentDetails;

/**
 *
 * @author Julio Lopez
 */
public class OCLPanel extends javax.swing.JPanel {

    public pojos.Login login;
    public String orNumber;
    
    public Server server;
    public String office;
    
    public DatabaseConnection db;
    public Connection connection;
    
    public ServiceAccounts activeAccount;
    
    /**
     * Paid bills area
     */
    public ORAssigning currentOr;
    int nextOrNumber = 0;
    double totalAmountPayable = 0;
    
    /**
     * Checks
     */
    public List<TransactionPaymentDetails> checkLists;
    Object[] checkColNames = {"Bank", "Check No", "Amount"};
    DefaultTableModel checkModel;
    
    boolean isOrLocked = true;
    
    public List<OCLMonthly> oclList;
    public DefaultTableModel oclModel;
    public Object[] oclColNames = {"*", "Month", "Amount To Pay"};
    
    public Collectibles collectible;
    public List<OCLMonthly> selectedList;
    
    /**
     * Creates new form OCLPanel
     */
    public OCLPanel(pojos.Login login, String orNumber) {
        this.orNumber = orNumber;
        this.login = login;
        initComponents();
        
        server = ConfigFileHelpers.getServer();
        office = ConfigFileHelpers.getOffice();
    
        db = new DatabaseConnection();
        connection = db.getDbConnectionFromDatabase(server);
        
        accountNumberSearch.requestFocus();
        checkLists = new ArrayList<>();
        oclList = new ArrayList<>();
        selectedList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumberSearch = new javax.swing.JFormattedTextField();
        advancedSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consumerAddress = new javax.swing.JTextField();
        consumerNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        meterNumber = new javax.swing.JTextField();
        accountNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isBapa = new javax.swing.JTextField();
        accountType = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        acctStatus = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        orNumberField = new javax.swing.JTextField();
        unlockOrNumberBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        NumberFormat format = NumberFormat.getInstance();
        format.setMinimumFractionDigits(2);
        format.setMaximumFractionDigits(2);
        format.setRoundingMode(RoundingMode.HALF_UP);
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Double.class);
        formatter.setAllowsInvalid(false);
        formatter.setCommitsOnValidEdit(true);
        cashPaymentField = new javax.swing.JFormattedTextField(formatter);
        jScrollPane2 = new javax.swing.JScrollPane();
        checkTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        addCheckButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        totalAmountPaid = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        transactBtn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        clearChecksBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        oclBalance = new javax.swing.JFormattedTextField(formatter);
        jLabel15 = new javax.swing.JLabel();
        monthsToPay = new javax.swing.JTextField();
        totalAmountToPay = new javax.swing.JFormattedTextField(formatter);
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oclTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receipt_long_FILL1_wght400_GRAD0_opsz20.png"))); // NOI18N
        jLabel1.setText("OCL Payments");
        jLabel1.setIconTextGap(10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Search Acount No:");

        accountNumberSearch.setForeground(new java.awt.Color(204, 0, 0));
        try {
            accountNumberSearch.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        accountNumberSearch.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        accountNumberSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountNumberSearchKeyReleased(evt);
            }
        });

        advancedSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        advancedSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/travel_explore_FILL0_wght700_GRAD0_opsz20.png"))); // NOI18N
        advancedSearch.setText("Advanced Search");
        advancedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedSearchActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Consumer Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Consumer Address:");

        consumerAddress.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        consumerNameField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Account Number:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Meter Number:");

        meterNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        accountNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Account Type:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("BAPA:");

        isBapa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        accountType.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Status:");

        acctStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Config", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 51, 0))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("OR Number");

        orNumberField.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        orNumberField.setForeground(new java.awt.Color(204, 0, 0));
        orNumberField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        orNumberField.setEnabled(false);

        unlockOrNumberBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_open_FILL1_wght400_GRAD0_opsz20.png"))); // NOI18N
        unlockOrNumberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockOrNumberBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orNumberField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unlockOrNumberBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orNumberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(unlockOrNumberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Cash Payment");

        cashPaymentField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        cashPaymentField.setEnabled(false);
        cashPaymentField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cashPaymentField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashPaymentFieldKeyReleased(evt);
            }
        });

        checkTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        checkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(checkTable);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Check Payments");

        addCheckButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addCheckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_FILL1_wght400_GRAD0_opsz20.png"))); // NOI18N
        addCheckButton.setText("Add Check");
        addCheckButton.setEnabled(false);
        addCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCheckButtonActionPerformed(evt);
            }
        });

        totalAmountPaid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        totalAmountPaid.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalAmountPaid.setEnabled(false);
        totalAmountPaid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Total Amount Paid");

        transactBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        transactBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check_circle_FILL1_wght400_GRAD0_opsz20.png"))); // NOI18N
        transactBtn.setText("Transact");
        transactBtn.setFocusable(false);
        transactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactBtnActionPerformed(evt);
            }
        });

        clearChecksBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clearChecksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_FILL1_wght400_GRAD0_opsz20.png"))); // NOI18N
        clearChecksBtn.setText("Clear Checks");
        clearChecksBtn.setEnabled(false);
        clearChecksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearChecksBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Total Balance");

        oclBalance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        oclBalance.setEnabled(false);
        oclBalance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        oclBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oclBalanceKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Months To Pay");

        monthsToPay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        monthsToPay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        monthsToPay.setEnabled(false);

        totalAmountToPay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalAmountToPay.setEnabled(false);
        totalAmountToPay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalAmountToPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalAmountToPayKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Current Payable");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(transactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addCheckButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearChecksBtn))
                            .addComponent(cashPaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalAmountToPay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(monthsToPay)
                            .addComponent(oclBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(oclBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthsToPay)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountToPay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cashPaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(addCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearChecksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        oclTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        oclTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        oclTable.setRowHeight(26);
        jScrollPane1.setViewportView(oclTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accountNumberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(advancedSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consumerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consumerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(meterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isBapa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acctStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(advancedSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountNumberSearch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(consumerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(acctStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(meterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(isBapa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountNumberSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNumberSearchKeyReleased
        String acctNo = accountNumberSearch.getText().trim();
        if (acctNo.length() == 12) {
            getAccountByOldAccountNo(acctNo);
        }
    }//GEN-LAST:event_accountNumberSearchKeyReleased

    private void advancedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedSearchActionPerformed
        advancedSearch();
    }//GEN-LAST:event_advancedSearchActionPerformed

    private void unlockOrNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockOrNumberBtnActionPerformed
        if (isOrLocked) {
            orNumberField.setEnabled(true);
            isOrLocked = false;
        } else {
            orNumberField.setEnabled(false);
            isOrLocked = true;
        }
    }//GEN-LAST:event_unlockOrNumberBtnActionPerformed

    private void cashPaymentFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashPaymentFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            showTransactConfirmation();
        } else {
            totalAmountPaid.setValue(getTotalAmountPaid());
        }
    }//GEN-LAST:event_cashPaymentFieldKeyReleased

    private void addCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCheckButtonActionPerformed
        try {
            cashPaymentField.setValue(null);
            totalAmountPaid.setValue(getTotalAmountPaid());

            JDialog checkDialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(getParent()));
            Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (int) size.getWidth();
            int y = (int) size.getHeight();
            checkDialog.setLocation(x/3, y/3);
            checkDialog.setTitle("Add Check");

            JPanel mainPanel = new JPanel(new GridLayout(0, 1, 0, 5));
            mainPanel.setBorder(new EmptyBorder(15, 15, 15, 15));

            mainPanel.add(new JLabel("Input Check Number"));
            JTextField checkNoField = new JTextField();
            checkNoField.setPreferredSize(new Dimension(400, 36));
            checkNoField.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(checkNoField);

            mainPanel.add(new JLabel("Input Check Amount"));
            NumberFormat format = NumberFormat.getInstance();
            format.setMinimumFractionDigits(2);
            format.setMaximumFractionDigits(2);
            format.setRoundingMode(RoundingMode.HALF_UP);
            NumberFormatter formatter = new NumberFormatter(format);
            formatter.setValueClass(Double.class);
            formatter.setAllowsInvalid(false);
            formatter.setCommitsOnValidEdit(true);
            JFormattedTextField amountField = new JFormattedTextField(formatter);
            amountField.setPreferredSize(new Dimension(400, 36));
            amountField.setFont(new Font("Arial", Font.BOLD, 16));
            amountField.setHorizontalAlignment(JTextField.RIGHT);
            amountField.setValue(totalAmountPayable);
            amountField.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            amountField.selectAll();
                        }
                    });
                }
            });
            mainPanel.add(amountField);

            mainPanel.add(new JLabel("Input Bank"));
            JTextField checkBank = new JTextField();
            checkBank.setPreferredSize(new Dimension(400, 36));
            checkBank.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(checkBank);

            JButton saveCheckBtn = new JButton("Add Check");
            saveCheckBtn.setFont(new Font("Arial", Font.PLAIN, 12));
            saveCheckBtn.setPreferredSize(new Dimension(100, 32));
            saveCheckBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check_circle_FILL1_wght400_GRAD0_opsz20.png")));
            mainPanel.add(saveCheckBtn);

            checkNoField.addKeyListener(new KeyListener() {
                @Override
                public void keyReleased(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                        amountField.requestFocus();
                    }
                }

                @Override
                public void keyTyped(KeyEvent e) {
                }
                @Override
                public void keyPressed(KeyEvent e) {
                }
            });

            amountField.addKeyListener(new KeyListener() {
                @Override
                public void keyReleased(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                        checkBank.requestFocus();
                    }
                }

                @Override
                public void keyTyped(KeyEvent e) {
                }
                @Override
                public void keyPressed(KeyEvent e) {
                }
            });

            checkBank.addKeyListener(new KeyListener() {
                @Override
                public void keyReleased(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                        checkLists.add(new TransactionPaymentDetails(
                            ObjectHelpers.generateIDandRandString(),
                            null,
                            amountField.getValue().toString(),
                            "Check",
                            checkBank.getText(),
                            checkNoField.getText(),
                            null,
                            nextOrNumber + "",
                            ObjectHelpers.getCurrentTimestamp(),
                            ObjectHelpers.getCurrentTimestamp()
                        ));

                        populateCheckTable();
                        checkDialog.dispose();
                        transactBtn.requestFocus();
                        totalAmountPaid.setValue(getTotalAmount());
                        cashPaymentField.requestFocus();
                    }
                }

                @Override
                public void keyTyped(KeyEvent e) {
                }
                @Override
                public void keyPressed(KeyEvent e) {
                }
            });

            saveCheckBtn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    checkLists.add(new TransactionPaymentDetails(
                            ObjectHelpers.generateIDandRandString(),
                            null,
                            amountField.getValue().toString(),
                            "Check",
                            checkBank.getText(),
                            checkNoField.getText(),
                            null,
                            nextOrNumber + "",
                            ObjectHelpers.getCurrentTimestamp(),
                            ObjectHelpers.getCurrentTimestamp()
                        ));

                    populateCheckTable();
                    checkDialog.dispose();
                    transactBtn.requestFocus();
                    totalAmountPaid.setValue(getTotalAmount());
                    cashPaymentField.requestFocus();
                }
            });

            checkDialog.add(mainPanel);
            checkDialog.pack();
            checkDialog.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Adding Check Payment", e.getMessage());
        }
    }//GEN-LAST:event_addCheckButtonActionPerformed

    private void transactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactBtnActionPerformed
        showTransactConfirmation();
    }//GEN-LAST:event_transactBtnActionPerformed

    private void clearChecksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearChecksBtnActionPerformed
        checkLists.clear();
        cashPaymentField.setValue(totalAmountPayable);
        totalAmountPaid.setValue(getTotalAmount());
        transactBtn.requestFocus();
        if (checkModel != null) {
            checkModel.getDataVector().removeAllElements();
            checkModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_clearChecksBtnActionPerformed

    private void oclBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oclBalanceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_oclBalanceKeyReleased

    private void totalAmountToPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalAmountToPayKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountToPayKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumber;
    private javax.swing.JFormattedTextField accountNumberSearch;
    private javax.swing.JTextField accountType;
    private javax.swing.JTextField acctStatus;
    private javax.swing.JButton addCheckButton;
    private javax.swing.JButton advancedSearch;
    private javax.swing.JFormattedTextField cashPaymentField;
    private javax.swing.JTable checkTable;
    private javax.swing.JButton clearChecksBtn;
    private javax.swing.JTextField consumerAddress;
    private javax.swing.JTextField consumerNameField;
    private javax.swing.JTextField isBapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField meterNumber;
    private javax.swing.JTextField monthsToPay;
    private javax.swing.JFormattedTextField oclBalance;
    private javax.swing.JTable oclTable;
    private javax.swing.JTextField orNumberField;
    private javax.swing.JFormattedTextField totalAmountPaid;
    private javax.swing.JFormattedTextField totalAmountToPay;
    private javax.swing.JButton transactBtn;
    private javax.swing.JButton unlockOrNumberBtn;
    // End of variables declaration//GEN-END:variables

    public void resetForm() {
        totalAmountPayable = 0;
        checkLists.clear();
    }
    
    public void getAccountByOldAccountNo(String oldAccountNo) {
        try {
            activeAccount = ServiceAccountsDao.getOneByOldAccountNumber(connection, oldAccountNo);
            
            resetForm();
            
            if (activeAccount != null) {
                addCheckButton.setEnabled(true);
                populateConsumerData();
                getOclData();
                cashPaymentField.setEnabled(true);
            } else {
                addCheckButton.setEnabled(false);
                Notifiers.showErrorMessage("Account Not Found", "Account not found! Verify the account number you inputted.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Fetching Account", e.getMessage());
        }
    }
    
    public void populateConsumerData() {
        try {
            consumerNameField.setText(activeAccount.getServiceAccountName());
            accountNumber.setText(activeAccount.getOldAccountNo());
            accountType.setText(activeAccount.getAccountType());
            isBapa.setText(activeAccount.getOrganization());
            consumerAddress.setText(ServiceAccountsDao.getAddress(activeAccount));
            acctStatus.setText(activeAccount.getAccountStatus());
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Populating Account Details", e.getMessage());
        }
    }
    
    public void advancedSearch() {
        try {
            JDialog advancedSearchDialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(getParent()));
            Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (int) size.getWidth();
            int y = (int) size.getHeight();
            advancedSearchDialog.setLocation(x/5, y/5);
            advancedSearchDialog.setTitle("Advanced Search");
            
            JPanel mainPanel = new JPanel();
    
            JTextField searchField = new javax.swing.JTextField();
            JButton searchBtn = new javax.swing.JButton();
            JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
            JTable resultsTable = new javax.swing.JTable();
            
            final String searchCols[] = {"Account No", "Consumer Name", "Address", "Account Type", "Status"};

            searchField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

            searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/travel_explore_FILL0_wght700_GRAD0_opsz20.png"))); // NOI18N
            
            // SEARCH
            searchField.addKeyListener(new KeyListener() {
                @Override
                public void keyTyped(KeyEvent e) {
                    
                }

                @Override
                public void keyPressed(KeyEvent e) {
                    
                }

                @Override
                public void keyReleased(KeyEvent e) {
                    DefaultTableModel searchTableModel;
                    if (searchField.getText().length() > 2) {
                        List<ServiceAccounts> results = ServiceAccountsDao.searchWithOcl(connection, searchField.getText());
                        int searchSize = results.size();
                        Object[][] searchData = new Object[searchSize][searchCols.length];
                        for (int i=0; i<searchSize; i++) {
                            ServiceAccounts acctt = results.get(i);
                            searchData[i][0] = acctt.getOldAccountNo();
                            searchData[i][1] = acctt.getServiceAccountName();
                            searchData[i][2] = ServiceAccountsDao.getAddress(acctt);
                            searchData[i][3] = acctt.getAccountType();
                            searchData[i][4] = acctt.getAccountStatus();
                        }
                        
                        searchTableModel = new DefaultTableModel(searchData, searchCols) {
                            @Override
                            public boolean isCellEditable(int row, int column) {
                                return false;
                            }                            
                        };
                    
                        resultsTable.setModel(searchTableModel);
                        resultsTable.getColumnModel().getColumn(0).setWidth(40);
                        resultsTable.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
                    }
                }
            });
            
            resultsTable.setRowHeight(28);
            resultsTable.setFont(new Font("Arial", Font.PLAIN, 12));
            
            jScrollPane1.setViewportView(resultsTable);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainPanel);
            mainPanel.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(searchBtn)
                    .addContainerGap(143, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            
            resultsTable.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (e.getClickCount() == 2) {
                        String acct = resultsTable.getModel().getValueAt(resultsTable.getSelectedRow(), 0).toString();
                        accountNumberSearch.setValue(acct);
                        getAccountByOldAccountNo(acct);
                        advancedSearchDialog.dispose();
                    }
                }                
            });
            
            advancedSearchDialog.add(mainPanel);
            advancedSearchDialog.pack();
            advancedSearchDialog.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Saving Transaction", e.getMessage());
        }
    }
    
    public void populateCheckTable() {
        try {
            clearChecksBtn.setEnabled(true);
            if (checkModel != null) {
                checkModel.getDataVector().removeAllElements();
                checkModel.fireTableDataChanged();
            }
            
            int checklistsize = checkLists.size();
            Object[][] data = new Object[checklistsize][checkColNames.length];
            for (int i=0; i<checklistsize; i++) {
                data[i][0] = checkLists.get(i).getBank();
                data[i][1] = checkLists.get(i).getCheckNo();
                data[i][2] = ObjectHelpers.roundTwo(checkLists.get(i).getAmount());
            }
            
            // DISPLAY TO TABLE
            checkModel = new DefaultTableModel(data, checkColNames);
            DefaultTableCellRenderer rightRendererBlue = new DefaultTableCellRenderer();
            rightRendererBlue.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererBlue.setFont(new Font("Arial", Font.BOLD, 14));
            rightRendererBlue.setForeground(Color.BLUE);

            checkTable.setModel(checkModel);
            checkTable.setRowHeight(25);
            checkTable.getColumnModel().getColumn(2).setCellRenderer(rightRendererBlue);
            checkTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            
            transactBtn.requestFocus();
            
            // VALIDATE TOTAL AMOUNT SELECTED
//            getSelectedBillsPayablesTotal();
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Getting Bills", e.getMessage());
        }
    }
    
    public void fetchOR() {
        currentOr = ORAssigningDao.getCurrentOR(connection, login.getId());
        if (currentOr != null) {
            nextOrNumber = Integer.parseInt(currentOr.getORumber()) + 1;
            orNumberField.setText(nextOrNumber + "");
            accountNumberSearch.requestFocus();
        } else {
            nextOrNumber = Integer.parseInt(orNumber);
            orNumberField.setText(nextOrNumber + "");
            accountNumberSearch.requestFocus();
        }            
    }
    
    public void getOclData() {
        try {
            resetForm();
            oclList.clear();
            
            collectible = CollectiblesDao.getOne(connection, activeAccount.getId());
            oclList.addAll(OCLMonthlyDao.getOclList(connection, activeAccount.getId()));
            
            if (collectible != null) {
                oclBalance.setValue(Double.valueOf(collectible.getBalance()));
                monthsToPay.setText(oclList.size() + "");
            }
            
            Object[][] data = new Object[oclList.size()][oclColNames.length];
            for (int i=0; i<oclList.size(); i++) {
                data[i][0] = false;
                data[i][1] = oclList.get(i).getServicePeriod();
                data[i][2] = ObjectHelpers.roundTwo(oclList.get(i).getAmount());
            }
            
            oclModel = new DefaultTableModel(data, oclColNames) {
                @Override
                public Class getColumnClass(int column) {
                    switch (column) {
                        case 0:
                            return Boolean.class;
                        case 1:
                            return String.class;
                        case 2:
                            return String.class;
                        default:
                            return null;
                    }
                }    

                @Override
                public boolean isCellEditable(int row, int column) {
                    if (column != 0) {
                        return false;
                    } else {
                        return true;
                    }                    
                }
            };
            
            oclTable.setModel(oclModel);
            oclTable.getColumnModel().getColumn(0).setMaxWidth(30);
            oclTable.getModel().addTableModelListener(new TableModelListener() {
                @Override
                public void tableChanged(TableModelEvent e) {
                    try {
                        totalAmountToPay.setValue(getTotalAmount());
                        cashPaymentField.setValue(getTotalAmount());
                        totalAmountPaid.setValue(Double.valueOf(cashPaymentField.getValue().toString()));
                        SwingUtilities.invokeLater(new Runnable() {
                            @Override
                            public void run() {
                                cashPaymentField.selectAll();
                                cashPaymentField.requestFocus();
                                cashPaymentField.setCaretPosition(0);
                            }
                        });
                    } catch (Exception ex) {
                        ex.printStackTrace();
                        Notifiers.showErrorMessage("Error Adding To Payments", ex.getMessage());
                    }
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Fetching OCL Data", e.getMessage());
        }
    }
    
    public double getTotalCheckPayments() {
        try {
             double ttl = 0;
             for(int i=0; i<checkLists.size(); i++) {
                ttl += Double.valueOf(checkLists.get(i).getAmount());
             }
             return ttl;
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }
    
    public double getTotalAmountPaid() {
        double cash = Double.valueOf(cashPaymentField.getValue() != null ? cashPaymentField.getValue().toString() : "0");
        double check = getTotalCheckPayments();
        return cash + check;
    }
    
    public double getTotalAmount() {
        try {
            totalAmountPayable = 0;
            selectedList.clear();
            for (int i = 0; i < oclModel.getRowCount(); i++) {
                if ((Boolean) oclModel.getValueAt(i,0)) {                      
                    totalAmountPayable += Double.valueOf(oclList.get(i).getAmount());
                    selectedList.add(oclList.get(i));
                }
            }
            return totalAmountPayable;
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }
    
    public void showTransactConfirmation() {
        try {
            // SHOW CONFIRMATION
            JDialog confirmationDialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(getParent()));
            Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (int) size.getWidth();
            int y = (int) size.getHeight();
            confirmationDialog.setLocation(x/3, y/3);
            confirmationDialog.setTitle("Payment Confirmation");

            JPanel mainPanel = new JPanel(new GridLayout(0, 2, 5, 5));
            mainPanel.setBorder(new EmptyBorder(15, 15, 15, 15));

            // CASH AMOUNT
            JLabel cashAmntLabel = new JLabel("CASH AMOUNT");
            cashAmntLabel.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(cashAmntLabel);

            NumberFormat format = NumberFormat.getInstance();
            format.setMinimumFractionDigits(2);
            format.setMaximumFractionDigits(2);
            format.setRoundingMode(RoundingMode.HALF_UP);
            NumberFormatter formatter = new NumberFormatter(format);
            formatter.setValueClass(Double.class);
            formatter.setAllowsInvalid(false);
            formatter.setCommitsOnValidEdit(true);

            JFormattedTextField cashAmountField = new JFormattedTextField(formatter);
            cashAmountField.setPreferredSize(new Dimension(250, 36));
            cashAmountField.setFont(new Font("Arial", Font.BOLD, 19)); 
            cashAmountField.setHorizontalAlignment(JTextField.RIGHT);
            cashAmountField.setValue(cashPaymentField.getValue());
            cashAmountField.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            cashAmountField.selectAll();
                        }
                    });                    
                }                
            });                

            mainPanel.add(cashAmountField);

            // CHECK AMOUNT
            JLabel checkAmount = new JLabel("CHECK AMOUNT");
            checkAmount.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(checkAmount);

            JFormattedTextField totalCheckAmountField = new JFormattedTextField(formatter);
            totalCheckAmountField.setPreferredSize(new Dimension(250, 36));
            totalCheckAmountField.setFont(new Font("Arial", Font.BOLD, 19)); 
            totalCheckAmountField.setHorizontalAlignment(JTextField.RIGHT);
            totalCheckAmountField.setValue(getTotalCheckPayments());
            totalCheckAmountField.setEnabled(false);
            mainPanel.add(totalCheckAmountField);

            // TOTAL AMOUNT PAID
            JLabel totalAmountPaidLabel = new JLabel("TOTAL AMOUNT PAID");
            totalAmountPaidLabel.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(totalAmountPaidLabel);                

            JFormattedTextField totalAmountPaidField = new JFormattedTextField(formatter);
            totalAmountPaidField.setPreferredSize(new Dimension(250, 36));
            totalAmountPaidField.setFont(new Font("Arial", Font.BOLD, 19)); 
            totalAmountPaidField.setHorizontalAlignment(JTextField.RIGHT);
            totalAmountPaidField.setValue(getTotalAmount());
            totalAmountPaidField.setEnabled(false);
            mainPanel.add(totalAmountPaidField);

            // TOTAL AMOUNT DUE
            JLabel totalAmountDueLabel = new JLabel("TOTAL AMOUNT DUE");
            totalAmountDueLabel.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(totalAmountDueLabel);                

            JFormattedTextField totalAmountDueField = new JFormattedTextField(formatter);
            totalAmountDueField.setPreferredSize(new Dimension(250, 36));
            totalAmountDueField.setFont(new Font("Arial", Font.BOLD, 19)); 
            totalAmountDueField.setForeground(Color.red);
            totalAmountDueField.setHorizontalAlignment(JTextField.RIGHT);
            totalAmountDueField.setValue(totalAmountPayable);
            mainPanel.add(totalAmountDueField);

            // TOTAL AMOUNT DUE
            JLabel changeLabel = new JLabel("CHANGE");
            changeLabel.setFont(new Font("Arial", Font.BOLD, 16));
            mainPanel.add(changeLabel);                

            JFormattedTextField changeField = new JFormattedTextField(formatter);
            changeField.setPreferredSize(new Dimension(250, 36));
            changeField.setFont(new Font("Arial", Font.BOLD, 19)); 
            changeField.setForeground(Color.BLUE);
            changeField.setHorizontalAlignment(JTextField.RIGHT);
            changeField.setValue(getTotalAmountPaid() - getTotalAmount());
            mainPanel.add(changeField);

            cashAmountField.addKeyListener(new KeyListener() {
                @Override
                public void keyTyped(KeyEvent e) {

                }
                @Override
                public void keyPressed(KeyEvent e) {

                }

                @Override
                public void keyReleased(KeyEvent e) {
                    try {
                        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                            transact();
                            confirmationDialog.dispose();
                        } else {
                            cashAmountField.commitEdit();
                            cashPaymentField.setValue(cashAmountField.getValue());
                            totalAmountPaid.setValue(getTotalAmountPaid());
                            totalAmountPaidField.setValue(getTotalAmountPaid());
                            changeField.setValue(getTotalAmountPaid() - getTotalAmount());  
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(PowerBillsPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

            JButton transactButton = new JButton("CONFIRM", new javax.swing.ImageIcon(getClass().getResource("/icons/check_circle_FILL1_wght400_GRAD0_opsz20.png")));
            transactButton.setFont(new Font("Arial", Font.BOLD, 18)); 
            transactButton.setPreferredSize(new Dimension(100, 40));
            mainPanel.add(new JLabel());
            mainPanel.add(transactButton);
            
            transactButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    transact();
                    confirmationDialog.dispose();
                }
            });

            confirmationDialog.add(mainPanel);
            confirmationDialog.pack();
            confirmationDialog.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Showing Payment Confirmation", e.getMessage());
        }
    }
    
    public void transact() {
        try {
            if (getTotalAmountPaid() >= getTotalAmount()) {
                if (oclList.size() > 0) {
                    // IF NAKA TERMED PAYMENT
                    // IF SELECTION IS MORE THAN 0
                    if (selectedList.size() > 0) {
                        /**
                         * UPDATE OCL TO PAID
                         */
                        String transId = ObjectHelpers.getTimeInMillis();

                        double ttl = 0;
                        List<TransactionDetails> detailsList = new ArrayList<>();
                        for (int i=0; i<selectedList.size(); i++) {
                            OCLMonthly ocl = selectedList.get(i);
                            OCLMonthlyDao.setOclPaid(connection, ocl.getId());
                            ttl += Double.valueOf(ocl.getAmount());

                            /**
                             * SAVE TRANSACTION DETAILS
                             */
                            TransactionDetails details = new TransactionDetails(
                                    ObjectHelpers.generateIDandRandString(),
                                    transId,
                                    "Termed arrear for " + selectedList.get(i).getServicePeriod(),
                                    selectedList.get(i).getAmount(),
                                    null,
                                    selectedList.get(i).getAmount(),
                                    DCRSummaryTransactionsDao.getARConsumersTermedPayments(activeAccount.getTownCode()),
                                    ObjectHelpers.getCurrentTimestamp(),
                                    ObjectHelpers.getCurrentTimestamp()
                            );
                            TransactionDetailsDao.insert(connection, details);
                            detailsList.add(details);

                            /**
                             * SAVE DCR
                             */
                            DCRSummaryTransactions dcr = new DCRSummaryTransactions(
                                ObjectHelpers.generateIDandRandString(),
                                DCRSummaryTransactionsDao.getARConsumersTermedPayments(activeAccount.getTownCode()),
                                null,
                                null,
                                selectedList.get(i).getAmount(),
                                ObjectHelpers.getSqlDate(),
                                ObjectHelpers.getSqlTime(),
                                login.getId(),
                                null,
                                null,
                                ObjectHelpers.getCurrentTimestamp(),
                                ObjectHelpers.getCurrentTimestamp(),
                                nextOrNumber + "",
                                "COLLECTION",
                                office,
                                activeAccount.getId());
                            DCRSummaryTransactionsDao.insert(connection, dcr);      
                        }

                        // DEDUCT BALANCE
                        if (collectible != null) {
                            double newBal = Double.valueOf(collectible.getBalance()) - ttl;
                            CollectiblesDao.updateCollectible(connection, collectible.getAccountNumber(), ObjectHelpers.roundTwoNoComma(newBal + ""));
                        } 

                        /**
                         * SAVE TO Transaction Details
                         */
                        String paymentUsed = "";
                        if (cashPaymentField.getValue() != null && checkLists.size() > 0) {
                            paymentUsed = "Cash and Check";
                        } else if (cashPaymentField.getValue() == null && checkLists.size() > 0) {
                            paymentUsed = "Check";
                        } else {
                            paymentUsed = "Cash";
                        }

                        TransactionIndex transaction = new TransactionIndex(
                                transId,
                                office + "-" + transId,
                                activeAccount.getServiceAccountName(),
                                "OCL Payment of " + activeAccount.getServiceAccountName(),
                                nextOrNumber + "",
                                ObjectHelpers.getSqlDate(),
                                null,
                                null,
                                ObjectHelpers.roundTwoNoComma(getTotalAmount()+ ""),
                                null,
                                login.getId(),
                                null,
                                null,
                                activeAccount.getId(),
                                "Arrears Termed Ledger",
                                paymentUsed,
                                null,
                                null,
                                null,
                                null,
                                null,
                                activeAccount.getServiceAccountName(),
                                null,
                                null, 
                                null,
                                activeAccount.getId(),
                                ObjectHelpers.getCurrentTimestamp(),
                                ObjectHelpers.getCurrentTimestamp()
                        );

                        TransactionIndexDao.insert(connection, transaction);

                        /**
                        * SAVE Transaction Logs
                        */
                       if (cashPaymentField.getValue() != null) {
                           TransactionPaymentDetails logs = new TransactionPaymentDetails(
                                   ObjectHelpers.generateIDandRandString(),
                                   transId,
                                   cashPaymentField.getValue().toString(),
                                   "Cash",
                                   null,
                                   null,
                                   null,
                                   nextOrNumber + "",
                                   ObjectHelpers.getCurrentTimestamp(),
                                   ObjectHelpers.getCurrentTimestamp()
                           );
                           TransactionPaymentDetailsDao.insert(connection, logs);
                       }
                       if (checkLists.size() > 0) {
                           for (int i=0; i<checkLists.size(); i++) {
                               TransactionPaymentDetails checkLogs = checkLists.get(i);
                               checkLogs.setTransactionIndexId(transId);
                               TransactionPaymentDetailsDao.insert(connection, checkLogs);
                           }
                       }

                        /*
                         * SAVE OR ASSIGNING
                         */
                        ORAssigning orNew = new ORAssigning(
                               ObjectHelpers.generateIDandRandString(),
                               orNumberField.getText(),
                               login.getId(),
                               ObjectHelpers.getSqlDate(),
                               null,
                               ObjectHelpers.getSqlTime(),
                               office,
                               ObjectHelpers.getCurrentTimestamp(),
                               ObjectHelpers.getCurrentTimestamp()
                        );
                        ORAssigningDao.insert(connection, orNew);
                        
                        /**
                         * PRINT HERE
                         */
                        print(transaction, detailsList, login.getUsername());

                       /**
                        * CLEAR AND RESET
                        */
                        resetForm();
                        fetchOR();
                        accountNumberSearch.setValue(null);
                        consumerNameField.setText("");
                        accountNumber.setText("");
                        accountType.setText("");
                        isBapa.setText("");
                        consumerAddress.setText("");
                        cashPaymentField.setValue(null);
                        cashPaymentField.setEnabled(false);
                        addCheckButton.setEnabled(false);
                        clearChecksBtn.setEnabled(false);
                        totalAmountPaid.setValue(null);
                        totalAmountToPay.setValue(null);
                        monthsToPay.setText(null);
                        oclBalance.setValue(null);
                        if (checkModel != null) {
                            checkModel.getDataVector().removeAllElements();
                            checkModel.fireTableDataChanged();
                        }
                        if (oclModel != null) {
                            oclModel.getDataVector().removeAllElements();
                            oclModel.fireTableDataChanged();
                        }
                        accountNumberSearch.requestFocus();
                    }
                } else {
                    // IF NAKA COLLECTIBLE LANG
                    if (getTotalAmountPaid() > 0) {
                        String transId = ObjectHelpers.getTimeInMillis();
                        
                        /**
                        * SAVE TRANSACTION DETAILS
                        */
                        List<TransactionDetails> detailsList = new ArrayList<>();
                        TransactionDetails details = new TransactionDetails(
                                ObjectHelpers.generateIDandRandString(),
                                transId,
                                "Termed arrear for Partial Payment",
                                getTotalAmountPaid() + "",
                                null,
                                getTotalAmountPaid() + "",
                                DCRSummaryTransactionsDao.getARConsumersTermedPayments(activeAccount.getTownCode()),
                                ObjectHelpers.getCurrentTimestamp(),
                                ObjectHelpers.getCurrentTimestamp()
                        );
                        TransactionDetailsDao.insert(connection, details);
                        detailsList.add(details);

                        /**
                         * SAVE DCR
                         */
                        DCRSummaryTransactions dcr = new DCRSummaryTransactions(
                            ObjectHelpers.generateIDandRandString(),
                            DCRSummaryTransactionsDao.getARConsumersTermedPayments(activeAccount.getTownCode()),
                            null,
                            null,
                            getTotalAmountPaid() + "",
                            ObjectHelpers.getSqlDate(),
                            ObjectHelpers.getSqlTime(),
                            login.getId(),
                            null,
                            null,
                            ObjectHelpers.getCurrentTimestamp(),
                            ObjectHelpers.getCurrentTimestamp(),
                            nextOrNumber + "",
                            "COLLECTION",
                            office,
                            activeAccount.getId());
                        DCRSummaryTransactionsDao.insert(connection, dcr);   
                        
                        /**
                         * SAVE TO Transaction Details
                         */
                        String paymentUsed = "";
                        if (cashPaymentField.getValue() != null && checkLists.size() > 0) {
                            paymentUsed = "Cash and Check";
                        } else if (cashPaymentField.getValue() == null && checkLists.size() > 0) {
                            paymentUsed = "Check";
                        } else {
                            paymentUsed = "Cash";
                        }

                        TransactionIndex transaction = new TransactionIndex(
                                transId,
                                office + "-" + transId,
                                activeAccount.getServiceAccountName(),
                                "OCL Payment of " + activeAccount.getServiceAccountName(),
                                nextOrNumber + "",
                                ObjectHelpers.getSqlDate(),
                                null,
                                null,
                                ObjectHelpers.roundTwoNoComma(getTotalAmountPaid()+ ""),
                                null,
                                login.getId(),
                                null,
                                null,
                                activeAccount.getId(),
                                "Arrears Termed Ledger",
                                paymentUsed,
                                null,
                                null,
                                null,
                                null,
                                null,
                                activeAccount.getServiceAccountName(),
                                null,
                                null, 
                                null,
                                activeAccount.getId(),
                                ObjectHelpers.getCurrentTimestamp(),
                                ObjectHelpers.getCurrentTimestamp()
                        );

                        TransactionIndexDao.insert(connection, transaction);
                        
                        // DEDUCT BALANCE
                        if (collectible != null) {
                            double newBal = Double.valueOf(collectible.getBalance()) - getTotalAmountPaid();
                            CollectiblesDao.updateCollectible(connection, collectible.getAccountNumber(), ObjectHelpers.roundTwoNoComma(newBal + ""));
                        } 
                        
                        /**
                        * SAVE Transaction Logs
                        */
                        if (cashPaymentField.getValue() != null) {
                            TransactionPaymentDetails logs = new TransactionPaymentDetails(
                                    ObjectHelpers.generateIDandRandString(),
                                    transId,
                                    cashPaymentField.getValue().toString(),
                                    "Cash",
                                    null,
                                    null,
                                    null,
                                    nextOrNumber + "",
                                    ObjectHelpers.getCurrentTimestamp(),
                                    ObjectHelpers.getCurrentTimestamp()
                            );
                            TransactionPaymentDetailsDao.insert(connection, logs);
                        }
                        if (checkLists.size() > 0) {
                            for (int i=0; i<checkLists.size(); i++) {
                                TransactionPaymentDetails checkLogs = checkLists.get(i);
                                checkLogs.setTransactionIndexId(transId);
                                TransactionPaymentDetailsDao.insert(connection, checkLogs);
                            }
                        }
                        
                        /*
                         * SAVE OR ASSIGNING
                         */
                        ORAssigning orNew = new ORAssigning(
                               ObjectHelpers.generateIDandRandString(),
                               orNumberField.getText(),
                               login.getId(),
                               ObjectHelpers.getSqlDate(),
                               null,
                               ObjectHelpers.getSqlTime(),
                               office,
                               ObjectHelpers.getCurrentTimestamp(),
                               ObjectHelpers.getCurrentTimestamp()
                        );
                        ORAssigningDao.insert(connection, orNew);
                        
                        /**
                         * PRINT HERE
                         */
                        print(transaction, detailsList, login.getUsername());

                       /**
                        * CLEAR AND RESET
                        */
                        resetForm();
                        fetchOR();
                        accountNumberSearch.setValue(null);
                        consumerNameField.setText("");
                        accountNumber.setText("");
                        accountType.setText("");
                        isBapa.setText("");
                        consumerAddress.setText("");
                        cashPaymentField.setValue(null);
                        cashPaymentField.setEnabled(false);
                        addCheckButton.setEnabled(false);
                        clearChecksBtn.setEnabled(false);
                        totalAmountPaid.setValue(null);
                        totalAmountToPay.setValue(null);
                        monthsToPay.setText(null);
                        oclBalance.setValue(null);
                        if (checkModel != null) {
                            checkModel.getDataVector().removeAllElements();
                            checkModel.fireTableDataChanged();
                        }
                        if (oclModel != null) {
                            oclModel.getDataVector().removeAllElements();
                            oclModel.fireTableDataChanged();
                        }
                        accountNumberSearch.requestFocus();
                    } else {
                        Notifiers.showErrorMessage("Insufficient Amount", "Insufficient Amount Provided");
                    }
                }                
            } else {
                Notifiers.showErrorMessage("Insufficient Amount", "Insufficient Amount Provided");
            }
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Saving Transaction", e.getMessage());
        }
    }
    
    public void print(TransactionIndex index, List<TransactionDetails> details, String username) {
        try {
            ServiceAccounts account = ServiceAccountsDao.getOneById(connection, index.getAccountNumber());
            
            PrinterJob job = PrinterJob.getPrinterJob();
            PageFormat pf = job.defaultPage();
            Paper paper = pf.getPaper();
            double width = 5d * 72d;
            double height = 4d * 72d;
            double margin = 0.1d * 72d;
            paper.setSize(width, height);
            paper.setImageableArea(
                    margin,
                    margin,
                    width - (margin * 2),
                    height - (margin * 2));
            pf.setPaper(paper);
            Book pBook = new Book();
            pBook.append(new TransactionsPrint(index, details, username, account), pf);
            job.setPageable(pBook);

    //            job.setPrintable(new PowerBillPrint(bills.get(i), account));
            try {
                job.print();
            } catch (PrinterException e) {
                e.printStackTrace();
                Notifiers.showErrorMessage("Error Printing Payment", "Transaction No: " + index.getId()+ "\n" + e.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Printing OR", e.getMessage());
        }
    }
}
